name: Playwright Tests

on:
  deployment_status:
jobs:
  run-e2e:
    if: github.event_name == 'deployment_status' && github.event.deployment_status.state == 'success'
    name: Run Playwright Tests
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/pnpm

      - name: Set Playwright path
        run: echo "PLAYWRIGHT_BROWSERS_PATH=$HOME/.cache/playwright-bin" >> $GITHUB_ENV
        shell: bash

      - name: Get installed Playwright version
        run: echo "PLAYWRIGHT_VERSION=$(cat package.json | grep \"@playwright/test | head -1 | awk '{ print $2 }' | sed 's/[",]//g')" >> $GITHUB_ENV
        shell: bash

      - name: Cache Playwright's binary
        id: playwright-cache
        uses: actions/cache@v4
        with:
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}
          path: ${{ env.PLAYWRIGHT_BROWSERS_PATH }}

      - name: Install Playwright Dependencies
        run: |
          pnpm playwright install --with-deps
        shell: bash

      - name: Run Playwright tests
        env:
          BASE_URL: ${{ github.event.deployment_status.environment_url }}
        run: pnpm test:e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
