name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate PR
    env:
      AUTH_SECRET: TBD
      AUTH_GITHUB_ID: TBD
      AUTH_GITHUB_SECRET: TBD
      DATABASE_URL: postgresql://postgres:password@localhost:6543/postgres
      DATABASE_DIRECT_URL: ${{ secrets.DEV_DATABASE_DIRECT_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/pnpm

      - name: Type check
        run: pnpm typecheck

      - name: Format check
        run: pnpm format:check

      # Disabling this for a bit, since Vercel should be doing this
      # - name: Lint
      #   run: pnpm lint

      # - name: Build
      #   run: pnpm build

      - name: Check that migrations were committed
        uses: ./.github/actions/migration
