name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate PR
    runs-on: ubuntu-latest
    env:
      AUTH_SECRET: TBD
      DATABASE_URL: mysql://user:password@localhost:3306/todo
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/pnpm

      - name: Type check
        run: pnpm typecheck

      - name: Format check
        run: pnpm format:check

      # Disabling this for a bit, since Vercel should be doing this
      # - name: Lint
      #   run: pnpm lint

      # - name: Build
      #   run: pnpm build

      - name: Generate DB migrations
        run: pnpm db:generate:all

      - name: Check that all migrations were committed
        run: git status --porcelain | grep -E 'drizzle/' || (echo "Migrations not committed" && exit 1)

      - name: Migrate Test DB
        run: pnpm db:migrate:test
