name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  validate:
    name: Validate PR
    env:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      POSTGRES_URL: ${{ secrets.DEV_POSTGRES_URL }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js and dependencies
        uses: ./.github/actions/pnpm

      - name: Type check
        run: pnpm typecheck

      - name: Format check
        run: pnpm format:check

      - name: Unit tests
        run: pnpm test:unit

      - name: Check that migrations were committed
        uses: ./.github/actions/migration
